# Auto-generated by auto_triage_ghostteam_wrongname.py (v3)
# REVIEW BEFORE RUNNING. These are real data changes (duplicate row deletes).
# Total auto-resolved deletes: 4

python mapping_conflict_audit.py delete --id D866A6ED-AD20-4CD3-A7E0-45A57891ED25 --investigation 36 --reason "Auto-triage v2 (H1_IDENTICAL_AFTER_NORMALIZE): 'Sand Springs Charles Page (OK)' and 'Sand Springs Charles Page (OK)' are the same name after normalization (same state)"
python mapping_conflict_audit.py delete --id E4D86A00-AC63-4759-85ED-15D5A1787F06 --investigation 109 --reason "Auto-triage v2 (H2_SUBSTRING_SAFE): 'Fort Sill (OK)' / 'Fort Sill Indian School (OK)' -- extra word(s) ['indian', 'school'] are non-identity-bearing filler"
python mapping_conflict_audit.py delete --id D63B7E7F-C87B-447A-BA0E-F24274FC5F52 --investigation 469 --reason "Auto-triage v2 (H1_IDENTICAL_AFTER_NORMALIZE): 'Chickasha (OK)' and 'Chickasha (OK)' are the same name after normalization (same state)"
python mapping_conflict_audit.py delete --id D18E583E-82AE-46CF-B263-BE1FCC5EA995 --investigation 1116 --reason "Auto-triage v2 (H1_IDENTICAL_AFTER_NORMALIZE): 'Chickasha (OK)' and 'Chickasha (OK)' are the same name after normalization (same state)"
