import pandas as pd
import pyodbc
import logging
import os

# --- CONFIGURATION ---
SERVER_NAME = "McKnights-PC\\SQLEXPRESS01"
DATABASE_NAME = "hs_football_database"
# Note: This file must be generated by the data preparation script
INPUT_FILE_PATH = "Mappable_Scores_Final.csv" 
# --- END CONFIGURATION ---

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def update_score_table_safe():
    """Reads cleaned game list and updates HS_Scores using the unique ID column."""
    
    # 1. READ CLEANED DATA
    logging.info(f"Reading cleaned game data from {INPUT_FILE_PATH}...")
    try:
        df = pd.read_csv(INPUT_FILE_PATH, encoding='latin1')
        
        # --- CRITICAL FIX: Clean up column names ---
        # This converts names like 'ID ' or 'id' to 'ID'
        df.columns = [col.strip().upper() for col in df.columns] 
        # --- END CRITICAL FIX ---
        
        logging.info(f"Loaded {len(df)} games for update. Columns found: {list(df.columns)}")
        
        # Safety Check: Ensure the ID column exists after cleanup
        if 'ID' not in df.columns:
            logging.error("FATAL: The 'ID' column (unique game identifier) was not found in the CSV.")
            return

    except FileNotFoundError:
        logging.error(f"FATAL: Input file not found: {INPUT_FILE_PATH}. Please run data_prep_workflow.py first.")
        return
    except Exception as e:
        logging.exception(f"An unexpected error occurred during file reading: {e}")
        return
    
    # 2. CONNECT TO DATABASE
    conn_str = f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={SERVER_NAME};DATABASE={DATABASE_NAME};Trusted_Connection=yes;'
    
    try:
        with pyodbc.connect(conn_str) as conn:
            cursor = conn.cursor()
            update_count = 0
            
            logging.info("Starting safe database update using unique Game ID...")

            for index, row in df.iterrows():
                # Access columns using the cleaned, uppercase name
                new_home_name = row['HOME'] 
                new_visitor_name = row['VISITOR']
                game_id = row['ID'] # Now safe to access

                # Safe UPDATE using the unique ID
                sql = """
                UPDATE [dbo].[HS_Scores]
                SET 
                    Home = ?,
                    Visitor = ?
                WHERE 
                    ID = ?;
                """
                
                # Parameters: (New Home, New Visitor, Game ID)
                params = (new_home_name, new_visitor_name, game_id)

                cursor.execute(sql, params)
                update_count += 1
                
                if update_count % 500 == 0:
                    conn.commit()
                    logging.info(f"Committed {update_count} updates...")

            # 3. FINAL COMMIT AND REPORT
            conn.commit()
            logging.info(f"SUCCESS: Finished safely updating {update_count} game records.")

    except pyodbc.Error as ex:
        logging.error("A critical SQL error occurred during update. Changes were rolled back.")
        logging.error(ex)
    except Exception as e:
        logging.exception(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    update_score_table_safe()